name: create-pr
description: Pushes changes to a new branch and creates PR

inputs:
  token:
    description: GitHub token for the target repo
    required: true
    type: string
  ssh_private_key:
    description: SSH private key to use with Git
    required: true
    type: string
  repo_path:
    description: Path of the cloned server and client repo
    retuired: true
    type: string

runs:
  using: composite
  steps:

  - uses: actions/checkout@v4
    with:
      repository: aydoughbombus/openapi-server-client
      token: ${{ inputs.token }}
      path: openapi-server-client
      fetch-depth: 0

  - name: Set up SSH
    shell: bash
    run: |
      mkdir -p ~/.ssh
      echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

      ssh-keyscan github.com >> ~/.ssh/known_hosts

  - name: Copy files over
    shell: bash
    run: |
      mkdir -p ${{ inputs.repo_path }}/pkg/gen/
      rsync -a --delete gen/ ${{ inputs.repo_path }}/pkg/gen/

  - name: Create branch
    working-directory: ${{ inputs.repo_path }}
    shell: bash
    run: |
      if ! git checkout -b 'AUTO-BRANCH-${{ github.ref_name }}' 2>/dev/null; then
        echo "Branch AUTO-BRANCH-${{ github.ref_name }} already exists. Skipping creation"
        git checkout 'AUTO-BRANCH-${{ github.ref_name }}'
      fi

  - name: Push changes to branch
    working-directory: ${{ inputs.repo_path }}
    shell: bash
    run: |
      git config user.name 'aydough-bot'
      git config user.email 'aydough-bot@non-existent.com'
      git add .
      git commit -m 'Automatic commit generated from aydoughbombus/openapi-specification@${{ github.sha }}'
      git push origin 'AUTO-BRANCH-${{ github.ref_name }}'

  - name: Open new PR
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.token }}
    run: |
      out=$(gh pr list --state open --base main --head AUTO-BRANCH-${{ github.ref_name }} --repo aydoughbombus/openapi-server-client --json number --jq '.[0].number'| xargs)
      if [[ -z "$out" ]]; then
        # No PR found - then let's open it
        gh pr create --title AUTO-PR-${{ github.ref_name }} --body 'PR automatically created'
      else
        echo "PR already exists, skipping creation"
      fi
  
  