OAPI_SPEC_NAME = oapi.yaml

SDK_NAME = sdk
API_NAME = api
GO_SUFFIX = gen.go

OAPI_SDK_NAME = $(SDK_NAME).$(GO_SUFFIX)
OAPI_API_NAME = $(API_NAME).$(GO_SUFFIX)

BUILD_DIR = build
SDK_BUILD_DIR = $(BUILD_DIR)/$(SDK_NAME)
API_BUILD_DIR = $(BUILD_DIR)/$(API_NAME)