OAPI_SPEC_NAME = oapi.yaml

SDK_NAME = sdk
API_NAME = api
GO_SUFFIX = gen.go

OAPI_SDK_NAME = $(SDK_NAME).$(GO_SUFFIX)
OAPI_API_NAME = $(API_NAME).$(GO_SUFFIX)

GENERATED_DIR = gen
SDK_GENERATED_DIR = $(GENERATED_DIR)/$(SDK_NAME)
API_GENERATED_DIR = $(GENERATED_DIR)/$(API_NAME)