name: init-repo
description: Inits the openapi-server-client repo to create a PR

inputs:
  token:
    description: GitHub token for the target repo
    required: true
    type: string
  path:
    description: Path to place the repository
    type: string
    default: openapi-server-client

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: aydoughbombus/openapi-server-client
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}

    - name: Create branch
      shell: bash
      run: |
        if ! git checkout -b 'AUTO-PR-${{ github.ref_name }}' 2>/dev/null; then
          echo "Branch AUTO-PR-${{ github.ref_name }} already exists. Skipping creation"
          git checkout 'AUTO-PR-${{ github.ref_name }}'
        fi

    - name: Check if PR exists
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh pr list --state open --base main --head AUTO-PR-${{ github.ref_name }} --repo aydoughbombus/openapi-server-client
    