name: main
on: push
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.12.0

            - name: Generate SDK
              shell: bash
              run: make build-sdk

            - name: Generate SDK
              shell: bash
              run: make build-sdk