name: main
on: push
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.12.0

            - name: Generate SDK
              shell: bash
              run: make build-sdk

            - name: Generate API
              shell: bash
              run: make build-api

            - uses: ./.github/actions/init-repo.yaml
              with:
                token: ${secrets.SERVER_CLIENT_TOKEN}