name: main
on: push
jobs:
    ci:
        runs-on: ubuntu-latest
        if: github.ref_name != 'main'
        steps:
            - uses: actions/checkout@v4

            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.12.0

            - name: Generate SDK
              shell: bash
              run: make build-sdk

            - name: Generate API
              shell: bash
              run: make build-api
            
            - uses: actions/checkout@v4
              with:
                repository: aydoughbombus/openapi-server-client
                token: ${{ secrets.SERVER_CLIENT_TOKEN }}
                path: openapi-server-client

            - name: Create PR
              uses: ./.github/actions/create-pr
              with:
                token: ${{ secrets.SERVER_CLIENT_TOKEN }}
                ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
                repo_path: openapi-server-client